// AUTO-GENERATED by scripts/sync-portfolio.mjs — do not edit by hand.
// Re-run the pipeline to update. Source of truth: portfolio.config.mjs + Supabase.
import type { Show } from "./shows";

export const shows: Show[] = [
  {
    "slug": "married-to-the-alpha",
    "title": {
      "en": "Married to the Alpha Who Ruined Me",
      "tr": "Beni Mahveden Alfa ile Evlendim"
    },
    "tagline": {
      "en": "She signed a 99-year marriage contract to save her mother. No one told her about the wolves.",
      "tr": "Annesini kurtarmak için 99 yıllık bir evlilik sözleşmesi imzaladı. Kurtlardan kimse söz etmedi."
    },
    "synopsis": {
      "en": "After the billionaire who destroyed her father offers to save her dying mother, Lena Ashford marries the man she hates — and learns on her wedding night that he isn't human, that an ancient bloodline runs in her veins, and that she is the one thing his pack has hunted for a hundred years. A supernatural romance in vertical episodes, produced in English and Turkish.",
      "tr": "Babasını mahveden milyarder, ölmek üzere olan annesini kurtarmayı teklif edince Lena Ashford nefret ettiği adamla evlenir — ve düğün gecesi onun insan olmadığını, damarlarında kadim bir kan hattının dolaştığını ve sürüsünün yüz yıldır avladığı tek şeyin kendisi olduğunu öğrenir. İngilizce ve Türkçe üretilen, dikey bölümlerden oluşan doğaüstü bir aşk."
    },
    "genre": "drama",
    "format": "series",
    "languages": [
      "EN",
      "TR"
    ],
    "primaryLang": "en",
    "poster": "/posters/ep-01.jpg",
    "social": {
      "en": {
        "youtube": "https://www.youtube.com/@alpharuinedme",
        "instagram": "https://www.instagram.com/alpharuinedme",
        "facebook": "https://www.facebook.com/1135959962931609",
        "tiktok": "https://www.tiktok.com/@alpharuinedme",
        "x": "https://x.com/AlphaRuinedMe"
      },
      "tr": {
        "youtube": "https://www.youtube.com/@mahvedenalfa",
        "instagram": "https://www.instagram.com/mahvedenalfa",
        "facebook": "https://www.facebook.com/1110443765489628",
        "tiktok": "https://www.tiktok.com/@mahvedenalfa",
        "x": "https://x.com/MahvedenAlfa"
      }
    },
    "episodes": [
      {
        "number": 1,
        "title": {
          "en": "The Devil's Offer",
          "tr": "Şeytanın Teklifi"
        },
        "synopsis": {
          "en": "To keep her dying mother on life support, Lena agrees to a billionaire stranger's impossible terms: a marriage contract, ninety-nine years, signed before midnight.",
          "tr": "Ölmek üzere olan annesini yaşatmak için Lena, bir milyarderin imkânsız şartlarını kabul eder: bir evlilik sözleşmesi, doksan dokuz yıl, gece yarısından önce imzalanacak."
        },
        "duration": "1:34",
        "poster": "/posters/ep-01.jpg",
        "video": {
          "en": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-01.en.mp4?v=2",
          "tr": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-01.tr.mp4?v=2"
        }
      },
      {
        "number": 2,
        "title": {
          "en": "The Wedding Night",
          "tr": "Düğün Gecesi"
        },
        "synopsis": {
          "en": "At the altar he says “mine,” not “I do” — and as wolves gather outside the estate, he demands she take off her mother's necklace.",
          "tr": "Nikâhta “evet” yerine “benim” der — ve malikânenin etrafında kurtlar toplanırken, annesinin kolyesini çıkarmasını ister."
        },
        "duration": "0:51",
        "poster": "/posters/ep-02.jpg",
        "video": {
          "en": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-02.en.mp4?v=2",
          "tr": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-02.tr.mp4?v=2"
        }
      },
      {
        "number": 3,
        "title": {
          "en": "What He Is",
          "tr": "Onun Sırrı"
        },
        "synopsis": {
          "en": "A portrait gallery gives up a secret: the necklace marks a Luna, the Alpha's mate — and for the first time Lena sees fear behind her husband's control.",
          "tr": "Bir portre galerisi sır veriyor: kolye bir Luna'yı, Alfa'nın eşini işaret ediyor — ve Lena ilk kez kocasının kontrolünün ardındaki korkuyu görüyor."
        },
        "duration": "1:14",
        "poster": "/posters/ep-03.jpg",
        "video": {
          "en": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-03.en.mp4?v=2",
          "tr": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-03.tr.mp4?v=2"
        }
      },
      {
        "number": 4,
        "title": {
          "en": "The Fiancée",
          "tr": "Nişanlı"
        },
        "synopsis": {
          "en": "The woman promised to Kael for twenty years arrives with a warning — his last wife's death was no accident, and nothing in his world ever is.",
          "tr": "Yirmi yıldır Kael'e vaat edilen kadın bir uyarıyla gelir — son eşinin ölümü kaza değildi, bu dünyada hiçbir şey asla kaza değil."
        },
        "duration": "0:59",
        "poster": "/posters/ep-04.jpg",
        "video": {
          "en": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-04.en.mp4?v=2",
          "tr": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-04.tr.mp4?v=2"
        }
      },
      {
        "number": 5,
        "title": {
          "en": "The Hospital",
          "tr": "Hastane"
        },
        "synopsis": {
          "en": "Lena's mother wakes with a plea and a revelation — never let him touch the necklace, and the charming friend from the wedding killed her father.",
          "tr": "Lena'nın annesi bir yalvarış ve bir itirafla uyanır — kolyeye asla dokundurma, ve düğündeki o cana yakın dost babasını öldürdü."
        },
        "duration": "1:02",
        "poster": "/posters/ep-05.jpg",
        "video": {
          "en": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-05.en.mp4?v=2",
          "tr": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-05.tr.mp4?v=2"
        }
      },
      {
        "number": 6,
        "title": {
          "en": "The Frame",
          "tr": "Tuzak"
        },
        "synopsis": {
          "en": "Kael admits the truth behind his ruined name: Damien framed him and left him for dead three years ago — and now Damien is at the door.",
          "tr": "Kael lekelenen adının ardındaki gerçeği itiraf eder: Damien üç yıl önce ona tuzak kurup onu ölüme terk etti — ve şimdi Damien kapıda."
        },
        "duration": "0:51",
        "poster": "/posters/ep-06.jpg",
        "video": {
          "en": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-06.en.mp4?v=2",
          "tr": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-06.tr.mp4?v=2"
        }
      },
      {
        "number": 7,
        "title": {
          "en": "The Forest",
          "tr": "Orman"
        },
        "synopsis": {
          "en": "Hunted by the pack, Kael runs Lena into the trees and shields her with his body — and she finally sees what he becomes.",
          "tr": "Sürü tarafından avlanırken Kael, Lena'yı ağaçların arasına kaçırır ve onu bedeniyle korur — ve Lena sonunda neye dönüştüğünü görür."
        },
        "duration": "1:12",
        "poster": "/posters/ep-07.jpg",
        "video": {
          "en": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-07.en.mp4?v=2",
          "tr": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-07.tr.mp4?v=2"
        }
      },
      {
        "number": 8,
        "title": {
          "en": "The Bloodline",
          "tr": "Kan Hattı"
        },
        "synopsis": {
          "en": "An ancient codex names what Lena is: the last Luna of the Crescent Pack, a bloodline that doesn't dilute — it waits.",
          "tr": "Kadim bir kodeks Lena'nın ne olduğunu söyler: Hilal Sürüsü'nün son Luna'sı, seyrelmeyen bir kan hattı — sadece bekler."
        },
        "duration": "1:29",
        "poster": "/posters/ep-08.jpg",
        "video": {
          "en": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-08.en.mp4?v=2",
          "tr": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-08.tr.mp4?v=2"
        }
      },
      {
        "number": 9,
        "title": {
          "en": "The Mark",
          "tr": "Mühür"
        },
        "synopsis": {
          "en": "Kael confesses he never married her to save her mother — he claimed her to keep every other Alpha away — as enemies surround the house.",
          "tr": "Kael, annesini kurtarmak için onunla evlenmediğini itiraf eder — onu her Alfa'dan uzak tutmak için sahiplendi — düşmanlar evi sararken."
        },
        "duration": "1:30",
        "poster": "/posters/ep-09.jpg",
        "video": {
          "en": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-09.en.mp4?v=2",
          "tr": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-09.tr.mp4?v=2"
        }
      },
      {
        "number": 10,
        "title": {
          "en": "The Brother",
          "tr": "Ağabey"
        },
        "synopsis": {
          "en": "Cornered by Seraphine's blade, Lena meets the one person she never knew existed — and learns the Crescent Pack never fell.",
          "tr": "Seraphine'in hançeriyle köşeye sıkışan Lena, var olduğunu hiç bilmediği biriyle tanışır — ve Hilal Sürüsü'nün hiç yok olmadığını öğrenir."
        },
        "duration": "1:24",
        "poster": "/posters/ep-10.jpg",
        "video": {
          "en": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-10.en.mp4?v=2",
          "tr": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-10.tr.mp4?v=2"
        }
      },
      {
        "number": 11,
        "title": {
          "en": "The Claim",
          "tr": "Sahiplenme"
        },
        "synopsis": {
          "en": "The Crescent Pack's claim turns a private marriage into open war.",
          "tr": "Hilal Sürüsü'nün talebi, özel bir evliliği açık bir savaşa çevirir."
        },
        "duration": "1:36",
        "poster": "/posters/ep-11.jpg",
        "video": {
          "en": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-11.en.mp4?v=2",
          "tr": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-11.en.mp4?v=2"
        }
      },
      {
        "number": 12,
        "title": {
          "en": "The Cost",
          "tr": "Bedel"
        },
        "synopsis": {
          "en": "Loyalties fracture as Lena learns what being a Luna will cost her.",
          "tr": "Luna olmanın bedelini öğrendikçe sadakatler çatlar."
        },
        "duration": "1:21",
        "poster": "/posters/ep-12.jpg",
        "video": {
          "en": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-12.en.mp4?v=2",
          "tr": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-12.en.mp4?v=2"
        }
      },
      {
        "number": 13,
        "title": {
          "en": "The Blade",
          "tr": "Hançer"
        },
        "synopsis": {
          "en": "An old promise and a silver blade force an impossible choice.",
          "tr": "Eski bir söz ve gümüş bir hançer imkânsız bir seçime zorlar."
        },
        "duration": "1:50",
        "poster": "/posters/ep-13.jpg",
        "video": {
          "en": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-13.en.mp4?v=2",
          "tr": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-13.en.mp4?v=2"
        }
      },
      {
        "number": 14,
        "title": {
          "en": "The Truth",
          "tr": "Gerçek"
        },
        "synopsis": {
          "en": "The truth about her father's death rewrites everything Lena thought she knew.",
          "tr": "Babasının ölümüyle ilgili gerçek, Lena'nın bildiği her şeyi yeniden yazar."
        },
        "duration": "1:21",
        "poster": "/posters/ep-14.jpg",
        "video": {
          "en": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-14.en.mp4?v=2",
          "tr": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-14.en.mp4?v=2"
        }
      },
      {
        "number": 15,
        "title": {
          "en": "The Reckoning",
          "tr": "Hesaplaşma"
        },
        "synopsis": {
          "en": "Two packs, one Luna, and a reckoning a hundred years in the making.",
          "tr": "İki sürü, tek bir Luna ve yüz yıllık bir hesaplaşma."
        },
        "duration": "1:29",
        "poster": "/posters/ep-15.jpg",
        "video": {
          "en": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-15.en.mp4?v=2",
          "tr": "https://pub-acd1440124614ccb9c0b6dcdfd9cd4af.r2.dev/married-to-the-alpha/ep-15.en.mp4?v=2"
        }
      }
    ],
    "episodeCount": 15,
    "order": 1
  },
  {
    "slug": "ahlak-masallari",
    "title": {
      "en": "Tales of Virtue",
      "tr": "Ahlak Masalları"
    },
    "tagline": {
      "en": "Small acts of kindness that ache — moral tales that stop a scrolling thumb.",
      "tr": "İnsanın içini titreten küçük iyilikler — kaydırmayı durduran ahlak masalları."
    },
    "synopsis": {
      "en": "A Turkish short-form series of self-contained moral tales — quiet, warm stories about kindness, honesty and mercy, each built to land an emotional gut-punch in just a few minutes.",
      "tr": "Kendi içinde tamamlanan ahlak masallarından oluşan kısa video serisi — iyilik, dürüstlük ve merhamet üzerine sıcak, sade hikâyeler; her biri birkaç dakika içinde yüreğe dokunmak için kurgulandı."
    },
    "genre": "moral",
    "format": "shorts",
    "languages": [
      "TR"
    ],
    "primaryLang": "tr",
    "poster": "/posters/ahlak-masallari/ep-01.jpg",
    "social": {
      "tr": {
        "youtube": "https://www.youtube.com/@ahlakmasallari",
        "instagram": "https://www.instagram.com/ahlakmasallari",
        "tiktok": "https://www.tiktok.com/@ahlakmasallari"
      }
    },
    "episodes": [
      {
        "number": 1,
        "title": {
          "en": "Eczanedeki Yabancı"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:55",
        "poster": "/posters/ahlak-masallari/ep-01.jpg",
        "video": {
          "tr": "https://pub-dacd753922ff4c0d94ea4ccecd7dd4a5.r2.dev/generated-assets/2fcbe6c3-7031-4454-84ea-70604f1c7538/videos/be56cc13-9f0a-405e-8d23-fdb9b74531c2.mp4"
        }
      },
      {
        "number": 2,
        "title": {
          "en": "Annenin Sofrası"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "2:11",
        "poster": "/posters/ahlak-masallari/ep-02.jpg",
        "video": {
          "tr": "https://pub-dacd753922ff4c0d94ea4ccecd7dd4a5.r2.dev/generated-assets/2fcbe6c3-7031-4454-84ea-70604f1c7538/videos/2680a00a-32ff-4262-94fd-910228bbc81f.mp4"
        }
      },
      {
        "number": 3,
        "title": {
          "en": "Emanet"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "2:52",
        "poster": "/posters/ahlak-masallari/ep-03.jpg",
        "video": {
          "tr": "https://pub-dacd753922ff4c0d94ea4ccecd7dd4a5.r2.dev/generated-assets/2fcbe6c3-7031-4454-84ea-70604f1c7538/videos/61bd4a07-fa2b-454a-94d5-8ab9116325ca.mp4"
        }
      },
      {
        "number": 4,
        "title": {
          "en": "Tevazu"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "2:15",
        "poster": "/posters/ahlak-masallari/ep-04.jpg",
        "video": {
          "tr": "https://pub-dacd753922ff4c0d94ea4ccecd7dd4a5.r2.dev/generated-assets/2fcbe6c3-7031-4454-84ea-70604f1c7538/videos/745507ee-9f11-4a82-95b1-c62e57b34936.mp4"
        }
      },
      {
        "number": 5,
        "title": {
          "en": "Komşu Hakkı"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "2:01",
        "poster": "/posters/ahlak-masallari/ep-05.jpg",
        "video": {
          "tr": "https://pub-dacd753922ff4c0d94ea4ccecd7dd4a5.r2.dev/generated-assets/2fcbe6c3-7031-4454-84ea-70604f1c7538/videos/9f5a063f-938b-420e-9d50-9133b50d6fab.mp4"
        }
      },
      {
        "number": 6,
        "title": {
          "en": "Koca Dolmuş Sustu: O Çocuk Ayağa Kalkınca 🚐"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:06",
        "poster": "/posters/ahlak-masallari/ep-06.jpg",
        "video": {
          "tr": "https://pub-dacd753922ff4c0d94ea4ccecd7dd4a5.r2.dev/generated-assets/2fcbe6c3-7031-4454-84ea-70604f1c7538/videos/018dd006-0b61-4819-a789-d80ec12bfa79.mp4"
        }
      },
      {
        "number": 7,
        "title": {
          "en": "Dükkânı Çökerken Onu Düşündü 🪵"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "2:15",
        "poster": "/posters/ahlak-masallari/ep-07.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/1ub58thce1/out.mp4"
        }
      },
      {
        "number": 8,
        "title": {
          "en": "Düştüğünde Kimse Görmedi — Çünkü Biri Önüne Geçmişti 🤍"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "2:28",
        "poster": "/posters/ahlak-masallari/ep-08.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/uyldelxtdy/out.mp4"
        }
      },
      {
        "number": 9,
        "title": {
          "en": "Babasının Öfkesini Bir Çocuk Nasıl Susturdu? 🚲"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "2:26",
        "poster": "/posters/ahlak-masallari/ep-09.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/h7p8lssm5c/out.mp4"
        }
      },
      {
        "number": 10,
        "title": {
          "en": "Aç Bir Çocuk Tek Ekmeğini İkiye Böldü 🍞"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "2:02",
        "poster": "/posters/ahlak-masallari/ep-10.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/7vjhwuftfn/out.mp4"
        }
      },
      {
        "number": 11,
        "title": {
          "en": "Zengin Adam Yağmurda Ağladı: Asıl Zengin Kimdi? 🌧️"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:09",
        "poster": "/posters/ahlak-masallari/ep-11.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/qozqp7dwh8/out.mp4"
        }
      },
      {
        "number": 12,
        "title": {
          "en": "Donmuş Yavruyu Görmezden Geldi — Sonra Geri Döndü 🐾"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "2:25",
        "poster": "/posters/ahlak-masallari/ep-12.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/vhhdqkm0mo/out.mp4"
        }
      },
      {
        "number": 13,
        "title": {
          "en": "Her Şeyi Vardı Ama Mutsuzdu — O Yoksul Çocuk Neden Gülüyordu? 🌅"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:52",
        "poster": "/posters/ahlak-masallari/ep-13.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/22jf2a25wp/out.mp4"
        }
      },
      {
        "number": 14,
        "title": {
          "en": "Kırılan Onu O Kırmadı 🪵"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "2:06",
        "poster": "/posters/ahlak-masallari/ep-14.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/3fli36zdl5/out.mp4"
        }
      },
      {
        "number": 15,
        "title": {
          "en": "Kapı Çalındığında Ellerinde Son Lokmaları Vardı 🌧️"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "2:11",
        "poster": "/posters/ahlak-masallari/ep-15.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/ad4qbu2h4y/out.mp4"
        }
      },
      {
        "number": 16,
        "title": {
          "en": "Kalabalıkta Kimse Onu Görmedi — Ta ki O Adam Durana Kadar 🤲"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:00",
        "poster": "/posters/ahlak-masallari/ep-16.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/59euanydao/out.mp4"
        }
      },
      {
        "number": 17,
        "title": {
          "en": "Bağıran Adam, Susan Usta 🤝"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:01",
        "poster": "/posters/ahlak-masallari/ep-17.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/zz3us5d7je/out.mp4"
        }
      },
      {
        "number": 18,
        "title": {
          "en": "Pazarda Yaşlı Kadını Kandırdılar — Kalabalık Sustu, Ama Bir Genç Sessiz Kalmadı ⚖️"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "2:24",
        "poster": "/posters/ahlak-masallari/ep-18.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/2udkrezvv9/out.mp4"
        }
      }
    ],
    "episodeCount": 18,
    "order": 2
  },
  {
    "slug": "jorsby-bilim",
    "title": {
      "en": "Jorsby Science",
      "tr": "Jorsby Bilim"
    },
    "tagline": {
      "en": "One astonishing true story a day — history, science and mysteries in 60 seconds.",
      "tr": "Her gün bir şaşırtıcı gerçek — tarih, bilim ve gizemler 60 saniyede."
    },
    "synopsis": {
      "en": "A high-cadence Turkish curiosity channel: sunken treasure, forgotten heists, scientific riddles and stranger-than-fiction history — each a tight vertical short built to be binged.",
      "tr": "Yüksek tempolu bir Türkçe merak kanalı: batık hazineler, unutulmuş soygunlar, bilimsel bilmeceler ve inanması güç tarih — her biri art arda izlenmek için kurgulanmış kısa dikey videolar."
    },
    "genre": "science",
    "format": "shorts",
    "languages": [
      "TR"
    ],
    "primaryLang": "tr",
    "poster": "/posters/jorsby-bilim/ep-01.jpg",
    "social": {
      "tr": {
        "youtube": "https://www.youtube.com/@jorsbybilim",
        "instagram": "https://www.instagram.com/jorsbybilim",
        "tiktok": "https://www.tiktok.com/@jorsbybilim"
      }
    },
    "episodes": [
      {
        "number": 1,
        "title": {
          "en": "İngilizce neden 'turkey' diyorlar? 🦃"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "0:59",
        "poster": "/posters/jorsby-bilim/ep-01.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/8cqz8winj4/out.mp4"
        }
      },
      {
        "number": 2,
        "title": {
          "en": "Tonlarca altın bu gemiyle battı ve 500 yıldır bulunamadı 💰"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "0:39",
        "poster": "/posters/jorsby-bilim/ep-02.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/8ugj7z72zr/out.mp4"
        }
      },
      {
        "number": 3,
        "title": {
          "en": "Naziler bu Alp gölünün dibine ne sakladı? 🤫"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:01",
        "poster": "/posters/jorsby-bilim/ep-03.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/30e9irb2lq/out.mp4"
        }
      },
      {
        "number": 4,
        "title": {
          "en": "Bu gemi battı, New York'un bankaları sarsıldı 💰🚢"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:03",
        "poster": "/posters/jorsby-bilim/ep-04.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/rcbnnnu1xc/out.mp4"
        }
      },
      {
        "number": 5,
        "title": {
          "en": "Uçaktan 3 km düştü, ormanda 11 gün yürüdü 🌿"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:09",
        "poster": "/posters/jorsby-bilim/ep-05.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/yp9cx9h14z/out.mp4"
        }
      },
      {
        "number": 6,
        "title": {
          "en": "Osmanlı kahveyi neden yasakladı? ☕"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:15",
        "poster": "/posters/jorsby-bilim/ep-06.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/er69w0su6h/out.mp4"
        }
      },
      {
        "number": 7,
        "title": {
          "en": "Kleopatra, Ay'a piramitlerden daha yakın yaşadı 🌙"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:08",
        "poster": "/posters/jorsby-bilim/ep-07.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/pqakptykjx/out.mp4"
        }
      },
      {
        "number": 8,
        "title": {
          "en": "Yüksekte neden 'atlasam mı' diye düşünürüz? 🧠"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:05",
        "poster": "/posters/jorsby-bilim/ep-08.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/pnow4v5zj3/out.mp4"
        }
      },
      {
        "number": 9,
        "title": {
          "en": "Bu firma eroini öksürük şurubu diye sattı 💊"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:04",
        "poster": "/posters/jorsby-bilim/ep-09.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/vr6ywtia4z/out.mp4"
        }
      },
      {
        "number": 10,
        "title": {
          "en": "Sahte üniformayla koca bir kasabayı ele geçirdi 🎖️"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:28",
        "poster": "/posters/jorsby-bilim/ep-10.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/219uoqqg4b/out.mp4"
        }
      },
      {
        "number": 11,
        "title": {
          "en": "Bir göktaşı koca ormanı yere serdi ama krater yok 💥"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:32",
        "poster": "/posters/jorsby-bilim/ep-11.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/zpbh6bat8u/out.mp4"
        }
      },
      {
        "number": 12,
        "title": {
          "en": "100 yıl kayıp sanılan elmas bir banka kasasındaymış 💎"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:24",
        "poster": "/posters/jorsby-bilim/ep-12.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/zt9jht880n/out.mp4"
        }
      },
      {
        "number": 13,
        "title": {
          "en": "Gökdelen fırtınada neden yıkılmıyor? Tepesindeki dev top 🏙️"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:23",
        "poster": "/posters/jorsby-bilim/ep-13.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/9osdcdsso5/out.mp4"
        }
      },
      {
        "number": 14,
        "title": {
          "en": "100 milyon dolarlık elması sıfır alarmla çaldılar 💎"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:19",
        "poster": "/posters/jorsby-bilim/ep-14.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/5n9i5biuxp/out.mp4"
        }
      },
      {
        "number": 15,
        "title": {
          "en": "1957'de koca bir ülke spagetti ağaçta yetişir sandı 🍝"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:20",
        "poster": "/posters/jorsby-bilim/ep-15.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/yptarxnveq/out.mp4"
        }
      },
      {
        "number": 16,
        "title": {
          "en": "Anestezi seni nasıl uyutuyor? Doktorlar tam bilmiyor 💉"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:19",
        "poster": "/posters/jorsby-bilim/ep-16.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/if390z0g67/out.mp4"
        }
      }
    ],
    "episodeCount": 16,
    "order": 3
  },
  {
    "slug": "buyuk-zihinler",
    "title": {
      "en": "Great Minds",
      "tr": "Büyük Zihinler"
    },
    "tagline": {
      "en": "History's greatest minds tell their own story — in their own voice.",
      "tr": "Tarihin en büyük zihinleri kendi hikâyesini kendi ağzından anlatıyor."
    },
    "synopsis": {
      "en": "First-person biographical documentaries in Turkish — Tesla, Marie Curie, Da Vinci, Einstein and more, each recounting their life and final regrets in their own voice.",
      "tr": "Türkçe, birinci ağızdan biyografik belgeseller — Tesla, Marie Curie, Da Vinci, Einstein ve daha fazlası; her biri hayatını ve son pişmanlıklarını kendi diliyle anlatıyor."
    },
    "genre": "history",
    "format": "series",
    "languages": [
      "TR"
    ],
    "primaryLang": "tr",
    "poster": "/posters/buyuk-zihinler/ep-01.jpg",
    "social": {
      "tr": {
        "youtube": "https://www.youtube.com/@buyukzihinler",
        "tiktok": "https://www.tiktok.com/@buyukzihinler"
      }
    },
    "episodes": [
      {
        "number": 1,
        "title": {
          "en": "Nikola Tesla"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "11:39",
        "poster": "/posters/buyuk-zihinler/ep-01.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/os0lrz6p2f/out.mp4"
        }
      },
      {
        "number": 2,
        "title": {
          "en": "İbn-i Sina"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "13:01",
        "poster": "/posters/buyuk-zihinler/ep-02.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/u3isxidj6u/out.mp4"
        }
      },
      {
        "number": 3,
        "title": {
          "en": "Marie Curie"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "12:35",
        "poster": "/posters/buyuk-zihinler/ep-03.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/1yog1vcg3x/out.mp4"
        }
      },
      {
        "number": 4,
        "title": {
          "en": "Leonardo da Vinci — Gülümseme"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "1:56",
        "poster": "/posters/buyuk-zihinler/ep-04.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/1zds50wba7/out.mp4"
        }
      },
      {
        "number": 5,
        "title": {
          "en": "Galileo Galilei — Eppur si muove"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "2:31",
        "poster": "/posters/buyuk-zihinler/ep-05.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/tgq3er6ks9/out.mp4"
        }
      },
      {
        "number": 6,
        "title": {
          "en": "Albert Einstein — İmza"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "2:51",
        "poster": "/posters/buyuk-zihinler/ep-06.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/fyuqsfuxph/out.mp4"
        }
      }
    ],
    "episodeCount": 6,
    "order": 4
  },
  {
    "slug": "kara-sayfa",
    "title": {
      "en": "The Black Page",
      "tr": "Kara Sayfa"
    },
    "tagline": {
      "en": "The chapters history would rather forget.",
      "tr": "Tarihin unutmak istediği sayfalar."
    },
    "synopsis": {
      "en": "Cinematic Turkish documentaries on the darkest chapters of Ottoman and world history — fratricide, palace intrigue and the price of power, told with restraint and dread.",
      "tr": "Osmanlı ve dünya tarihinin en karanlık sayfaları üzerine sinematik Türkçe belgeseller — kardeş katli, saray entrikaları ve iktidarın bedeli; ölçülü ve ürpertici bir dille."
    },
    "genre": "dark-history",
    "format": "series",
    "languages": [
      "TR"
    ],
    "primaryLang": "tr",
    "poster": "/posters/kara-sayfa/ep-01.jpg",
    "social": {
      "tr": {
        "youtube": "https://www.youtube.com/@karasayfahikayeler"
      }
    },
    "episodes": [
      {
        "number": 1,
        "title": {
          "en": "Bir Gecede On Dokuz Kardeş"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "6:29",
        "poster": "/posters/kara-sayfa/ep-01.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/bttla0jfsx/out.mp4"
        }
      },
      {
        "number": 2,
        "title": {
          "en": "Kafesin İçindeki Valide"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "6:07",
        "poster": "/posters/kara-sayfa/ep-02.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/cmd68t30k7/out.mp4"
        }
      },
      {
        "number": 3,
        "title": {
          "en": "Tahtın Kırıldığı Gece"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "7:26",
        "poster": "/posters/kara-sayfa/ep-03.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/o9musvyrnk/out.mp4"
        }
      },
      {
        "number": 4,
        "title": {
          "en": "Kanuni, kendi oğlunu bir çadırda boğdurdu"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "2:30",
        "poster": "/posters/kara-sayfa/ep-04.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/ibiiu3acny/out.mp4"
        }
      }
    ],
    "episodeCount": 4,
    "order": 5
  },
  {
    "slug": "para-hikayeleri",
    "title": {
      "en": "Money Stories",
      "tr": "Para Hikayeleri"
    },
    "tagline": {
      "en": "How fortunes are built — and how they collapse overnight.",
      "tr": "Servetler nasıl kurulur — ve bir gecede nasıl çöker."
    },
    "synopsis": {
      "en": "Turkish business documentaries on spectacular rises and falls — billion-dollar startups, pyramid schemes and the anatomy of financial collapse, told like true-crime.",
      "tr": "Görkemli yükseliş ve çöküşler üzerine Türkçe iş belgeselleri — milyar dolarlık girişimler, saadet zincirleri ve finansal çöküşün anatomisi; suç dosyası tadında."
    },
    "genre": "finance",
    "format": "series",
    "languages": [
      "TR"
    ],
    "primaryLang": "tr",
    "poster": "/posters/para-hikayeleri/ep-01.jpg",
    "social": {
      "tr": {
        "youtube": "https://www.youtube.com/@girisimseruvenleri"
      }
    },
    "episodes": [
      {
        "number": 1,
        "title": {
          "en": "Getir: On İki Milyar Dolardan Hiçliğe"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "5:48",
        "poster": "/posters/para-hikayeleri/ep-01.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/vpw23tit2d/out.mp4"
        }
      },
      {
        "number": 2,
        "title": {
          "en": "Çiftlik Bank: Sanal İneklerle Kurulan Milyarlık Yalan"
        },
        "synopsis": {
          "en": ""
        },
        "duration": "3:52",
        "poster": "/posters/para-hikayeleri/ep-02.jpg",
        "video": {
          "tr": "https://s3.us-east-1.amazonaws.com/remotionlambda-useast1-hja8y0cbwi/renders/riv0bedl79/out.mp4"
        }
      }
    ],
    "episodeCount": 2,
    "order": 6
  }
];
